#!/usr/bin/env bash

source ./constants.sh

# Return true if the a file already exists in /usr/local/bin under the same name
# and it was **NOT** generated by this script
non_generated_bin_already_exists() {
    if [[ -f "${app_bin}" ]]; then
        if cat "${app_bin}" | grep -E "^${FILE_STAMP}\$" >/dev/null 2>&1; then
            return 1
        fi
        return 0
    fi

    return 1
}

create_bin() {
    echo -e "#!/usr/bin/env bash\n" | sudo tee "${app_bin}" >/dev/null 2>&1
    sudo chmod +x "${app_bin}"
}

append_line_to_script() {
    local script_line="${1}"
    echo -e "${script_line}" | sudo tee -a "${app_bin}" >/dev/null 2>&1
}

get_apps() {
    flatpak list --app --columns=application
}

get_longest_app_id() {
    local longest=0

    while IFS= read -r app_id; do
        local len="${#app_id}"
        ((longest < len)) && longest=$len
    done < <(get_apps)

    echo $longest
}

main() {
    echo -e "Running flatbin.sh..."
    echo -e "This script creates proxies for flatpak scripts in /usr/local/bin"
    echo -e "Run ./remove_proxies.sh to remove the executables generated by this script"
    echo -e "Creating proxies..."

    local longest_app_id=$(get_longest_app_id)

    # Iterate installed flatpak apps
    while IFS= read -r app_id; do
        app_command=$(flatpak info --show-metadata "${app_id}" | grep '^command=' | awk -F '=' '{print $2}')
        app_bin="/usr/local/bin/${app_command}"

        # Generate executable
        if non_generated_bin_already_exists; then
            printf "Skipping ${app_id}. Non-generated file already exists at ${app_bin}\n"
            continue
        fi

        create_bin
        append_line_to_script 'if [[ "${1}" == "--version" || "${1}" == "-v" ]]; then'
        append_line_to_script "\t# prefix version results with flatpak since flatpak versions may vary between sources"
        append_line_to_script "\tflatpak info ${app_id} | grep Version | awk '{print \"flatpak\", \$2}'"
        append_line_to_script "\texit 0"
        append_line_to_script "fi"
        append_line_to_script "flatpak run ${app_id} \"\${@}\""
        append_line_to_script "\n${FILE_STAMP}"

        # Log executable path for optional future removal
        if ! grep "${app_bin}" "${PROXIES}" >/dev/null 2>&1; then
            echo "${app_bin}" >> "${PROXIES}"
        fi


        ansi_len=9

        printf "%-$((longest_app_id + ansi_len + 1))b%b%b" \
            "\033[33m${app_id}\033[0m" \
            "\033[33m⇒ \033[0m" \
            "\033[32m${app_command}\033[0m\n"

    done < <(get_apps)
}

main
